# fly.toml app configuration file generated for morning-sound-5698 on 2023-06-05T16:01:19+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "morning-sound-5698"
primary_region = "sin"
kill_signal = "SIGTERM"

[deploy]
  release_command = "/app/bin/migrate"

[env]
  PHX_HOST = "morning-sound-5698.fly.dev"
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  [http_service.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 1000
